# Generated by Django 4.2.5 on 2023-09-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_contact_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='picture',
        ),
    ]
